package uk.dansvlogs.clinicalwatch

import android.Manifest
import android.content.*
import android.content.pm.PackageManager
import android.graphics.*
import android.graphics.drawable.Drawable
import android.hardware.*
import android.os.*
import android.util.Base64
import android.view.*
import androidx.core.content.ContextCompat
import java.text.SimpleDateFormat
import java.util.*
import kotlin.math.*

class ClinicalWatchView(context: Context) : View(context), SensorEventListener {
 private val paint=Paint(Paint.ANTI_ALIAS_FLAG); private val handler=Handler(Looper.getMainLooper()); private val sensors=context.getSystemService(Context.SENSOR_SERVICE) as SensorManager; private val heart=sensors.getDefaultSensor(Sensor.TYPE_HEART_RATE); private val prefs=context.getSharedPreferences("companion",Context.MODE_PRIVATE)
 private var ambient=false;private var watchBattery=0;private var steps:Long?=null;private var phoneBattery:Int?=null;private var pulse:Int?=null;private var mode=0;private var running=false;private var stopwatchBase=0L;private var stopwatchElapsed=0L;private var accent=Color.rgb(190,235,0);private val text=Color.rgb(238,241,229);private var displayName="DAN";private var customCrest:Bitmap?=null;private var heartRegistered=false;private val defaultCrest:Drawable? by lazy{ContextCompat.getDrawable(context,R.drawable.crest)}
 private val dataReceiver=object:BroadcastReceiver(){override fun onReceive(c:Context?,i:Intent?){loadCompanion();invalidate()}};private val batteryReceiver=object:BroadcastReceiver(){override fun onReceive(c:Context?,i:Intent?){val l=i?.getIntExtra(BatteryManager.EXTRA_LEVEL,-1)?:-1;val s=i?.getIntExtra(BatteryManager.EXTRA_SCALE,-1)?:-1;if(l>=0&&s>0)watchBattery=l*100/s}};private val ticker=object:Runnable{override fun run(){invalidate();handler.postDelayed(this,if(mode==1&&running&&!ambient)100 else 1000)}}
 private val gestures=GestureDetector(context,object:GestureDetector.SimpleOnGestureListener(){override fun onDown(e:MotionEvent)=true;override fun onDoubleTap(e:MotionEvent):Boolean{val dx=e.x-width/2f;val dy=e.y-height/2f;if(dx*dx+dy*dy<(min(width,height)*.34f).pow(2)){mode=1-mode;restart();return true};return false}})
 init{context.registerReceiver(batteryReceiver,IntentFilter(Intent.ACTION_BATTERY_CHANGED));ContextCompat.registerReceiver(context,dataReceiver,IntentFilter("uk.dansvlogs.clinicalwatch.DATA_CHANGED"),ContextCompat.RECEIVER_NOT_EXPORTED);loadCompanion();handler.post(ticker)}
 private fun loadCompanion(){displayName=prefs.getString("name","DAN")?:"DAN";try{accent=Color.parseColor(prefs.getString("accent","#BEEB00"))}catch(_:Throwable){};steps=prefs.getString("steps",null)?.toLongOrNull()?:steps;phoneBattery=prefs.getString("phoneBattery",null)?.toIntOrNull()?:phoneBattery;customCrest=try{prefs.getString("crest",null)?.let{val b=Base64.decode(it,Base64.DEFAULT);BitmapFactory.decodeByteArray(b,0,b.size)}}catch(_:Throwable){null}}
 fun setAmbient(v:Boolean){ambient=v;if(v)stopSensors() else startSensors();restart()};fun setExternalSteps(v:Long){steps=v.coerceAtLeast(0);invalidate()}
 fun startSensors(){if(heartRegistered)return;val body=ContextCompat.checkSelfPermission(context,Manifest.permission.BODY_SENSORS)==PackageManager.PERMISSION_GRANTED;val health=if(Build.VERSION.SDK_INT>=36)ContextCompat.checkSelfPermission(context,"android.permission.health.READ_HEART_RATE")==PackageManager.PERMISSION_GRANTED else false;val allowed=if(Build.VERSION.SDK_INT>=36)health else body;if(allowed&&heart!=null){heartRegistered=sensors.registerListener(this,heart,SensorManager.SENSOR_DELAY_NORMAL)}}
 fun stopSensors(){if(heartRegistered){sensors.unregisterListener(this,heart);heartRegistered=false}}
 override fun onSensorChanged(e:SensorEvent){if(e.sensor.type==Sensor.TYPE_HEART_RATE&&e.values.isNotEmpty()){val raw=e.values[0];if(raw.isFinite()){val v=raw.roundToInt();if(v in 25..240)pulse=v};invalidate()}};override fun onAccuracyChanged(s:Sensor?,a:Int){};private fun restart(){handler.removeCallbacks(ticker);handler.post(ticker)};private fun elapsed()=if(running)SystemClock.elapsedRealtime()-stopwatchBase else stopwatchElapsed;private fun toggle(){if(running){stopwatchElapsed=elapsed();running=false}else{stopwatchBase=SystemClock.elapsedRealtime()-stopwatchElapsed;running=true};restart()};private fun reset(){running=false;stopwatchElapsed=0;stopwatchBase=SystemClock.elapsedRealtime();restart()}
 override fun onTouchEvent(e:MotionEvent):Boolean{if(gestures.onTouchEvent(e))return true;if(e.action==MotionEvent.ACTION_UP&&mode==1&&!ambient&&e.y>height*.66f&&e.y<height*.89f){if(e.x<width/2)toggle()else reset();return true};return true};override fun onDetachedFromWindow(){stopSensors();handler.removeCallbacks(ticker);try{context.unregisterReceiver(batteryReceiver)}catch(_:Exception){};try{context.unregisterReceiver(dataReceiver)}catch(_:Exception){};super.onDetachedFromWindow()}
 override fun onDraw(c:Canvas){c.drawColor(Color.BLACK);val cx=width/2f;val cy=height/2f;val r=min(width,height)*.495f;face(c,cx,cy,r);if(mode==0)clock(c,cx,cy,r)else stopwatch(c,cx,cy,r)}
 private fun face(c:Canvas,cx:Float,cy:Float,r:Float){paint.style=Paint.Style.FILL;paint.shader=RadialGradient(cx,cy,r,intArrayOf(Color.rgb(32,34,32),Color.rgb(10,12,11),Color.BLACK),floatArrayOf(0f,.66f,1f),Shader.TileMode.CLAMP);c.drawCircle(cx,cy,r*.985f,paint);paint.shader=null;for(k in 0..3){paint.style=Paint.Style.STROKE;paint.color=Color.rgb(38+k*11,42+k*11,39+k*11);paint.strokeWidth=r*(.010f+k*.003f);c.drawCircle(cx,cy,r*(.965f-k*.033f),paint)};for(i in 0 until 60){val a=Math.toRadians((i*6-90).toDouble());val major=i%5==0;val o=r*.905f;val inn=o-r*(if(major).082f else .032f);paint.color=if(i%15==0&&!ambient)accent else if(major)text else Color.rgb(150,155,150);paint.strokeWidth=r*(if(major).024f else .0055f);paint.strokeCap=Paint.Cap.SQUARE;c.drawLine(cx+cos(a).toFloat()*inn,cy+sin(a).toFloat()*inn,cx+cos(a).toFloat()*o,cy+sin(a).toFloat()*o,paint);if(major&&!ambient){val n=if(i==0)"60" else "%02d".format(i);label(c,n,cx+cos(a).toFloat()*r*.765f,cy+sin(a).toFloat()*r*.765f+r*.025f,r*.055f,if(i%15==0)accent else text,true)}}}
 private fun polygonPanel(c:Canvas,l:Float,t:Float,rr:Float,b:Float,stroke:Int=Color.rgb(72,78,73)){val cut=min(rr-l,b-t)*.13f;val p=Path().apply{moveTo(l+cut,t);lineTo(rr-cut,t);lineTo(rr,t+cut);lineTo(rr,b-cut);lineTo(rr-cut,b);lineTo(l+cut,b);lineTo(l,b-cut);lineTo(l,t+cut);close()};paint.style=Paint.Style.FILL;paint.color=Color.rgb(6,9,7);c.drawPath(p,paint);paint.style=Paint.Style.STROKE;paint.strokeWidth=min(width,height)*.009f;paint.color=Color.rgb(28,32,29);c.drawPath(p,paint);paint.strokeWidth=min(width,height)*.004f;paint.color=stroke;c.drawPath(p,paint)}
 private fun crest(c:Canvas,cx:Float,top:Float,r:Float){customCrest?.let{val hh=r*.30f;val ww=hh*it.width/it.height.toFloat();c.drawBitmap(it,null,RectF(cx-ww/2,top,cx+ww/2,top+hh),paint);return};defaultCrest?.let{val hh=(r*.30f).toInt();val ww=(hh*.8f).toInt();it.setBounds((cx-ww/2).toInt(),top.toInt(),(cx+ww/2).toInt(),top.toInt()+hh);it.draw(c)}}
 private fun clock(c:Canvas,cx:Float,cy:Float,r:Float){val cal=Calendar.getInstance();val sec=cal.get(Calendar.SECOND);val min=cal.get(Calendar.MINUTE);val hour=cal.get(Calendar.HOUR);if(!ambient){crest(c,cx,cy-r*.72f,r);label(c,"PARAMEDIC",cx,cy-r*.385f,r*.058f,text,true);label(c,displayName.uppercase(Locale.getDefault()),cx,cy-r*.265f,r*.086f,accent,true);metric(c,cx-r*.515f,cy-r*.025f,"STEPS",steps?.let{"%,d".format(it)}?:"--","⌁");metric(c,cx+r*.515f,cy-r*.025f,"PULSE",pulse?.let{"$it"}?:"--","♥",if(pulse==null)"" else "BPM");digitalClock(c,cx,cy+r*.29f,SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(Date()),SimpleDateFormat("EEE d MMM yyyy",Locale.getDefault()).format(Date()).uppercase(Locale.getDefault()));battery(c,cx-r*.295f,cy+r*.685f,"WATCH",watchBattery);battery(c,cx+r*.295f,cy+r*.685f,"PHONE",phoneBattery);star(c,cx,cy+r*.705f,r*.070f)};val m=min+sec/60f;hand(c,cx,cy,r*.40f,(hour+m/60)*30,r*.072f);hand(c,cx,cy,r*.61f,m*6,r*.049f);second(c,cx,cy,r,sec*6f);hub(c,cx,cy,r)}
 private fun metric(c:Canvas,x:Float,y:Float,t:String,v:String,icon:String,unit:String=""){val r=min(width,height)*.495f;polygonPanel(c,x-r*.235f,y-r*.215f,x+r*.235f,y+r*.215f);label(c,icon,x,y-r*.105f,r*.075f,accent,true);label(c,t,x,y+r*.005f,r*.055f,text,true);label(c,v,x,y+r*.135f,r*.100f,accent,true);if(unit.isNotEmpty())label(c,unit,x,y+r*.205f,r*.043f,text,true);if(t=="STEPS"&&steps!=null){val progress=((steps!!%10000)/10000f).coerceIn(0f,1f);val left=x-r*.155f;val yy=y+r*.177f;for(i in 0..5){paint.style=Paint.Style.FILL;paint.color=if(i/6f<=progress)accent else Color.rgb(45,48,45);c.drawRect(left+i*r*.052f,yy,left+i*r*.052f+r*.040f,yy+r*.031f,paint)}}}
 private fun digitalClock(c:Canvas,x:Float,y:Float,v:String,s:String){val r=min(width,height)*.495f;polygonPanel(c,x-r*.455f,y-r*.185f,x+r*.455f,y+r*.215f,accent);label(c,"24H",x-r*.345f,y-r*.092f,r*.046f,accent,true);label(c,v,x,y+r*.020f,r*.145f,text,true);paint.style=Paint.Style.STROKE;paint.strokeWidth=r*.0045f;paint.color=Color.rgb(83,88,83);c.drawLine(x-r*.37f,y+r*.100f,x+r*.37f,y+r*.100f,paint);label(c,"▣  $s",x,y+r*.177f,r*.046f,Color.LTGRAY,true)}
 private fun battery(c:Canvas,x:Float,y:Float,t:String,v:Int?){val r=min(width,height)*.495f;label(c,t,x,y-r*.050f,r*.037f,text,true);paint.style=Paint.Style.STROKE;paint.strokeWidth=r*.007f;paint.color=accent;c.drawRoundRect(x-r*.105f,y,x+r*.085f,y+r*.060f,r*.008f,r*.008f,paint);c.drawRect(x+r*.085f,y+r*.017f,x+r*.107f,y+r*.043f,paint);label(c,v?.let{"$it%"}?:"--",x,y+r*.137f,r*.052f,accent,true)}
 private fun star(c:Canvas,x:Float,y:Float,size:Float){paint.style=Paint.Style.STROKE;paint.strokeWidth=size*.14f;paint.color=accent;val p=Path();for(i in 0 until 12){val a=Math.toRadians((-90+i*30).toDouble());val rad=if(i%2==0)size else size*.48f;val px=x+cos(a).toFloat()*rad;val py=y+sin(a).toFloat()*rad;if(i==0)p.moveTo(px,py)else p.lineTo(px,py)};p.close();c.drawPath(p,paint)}
 private fun stopwatch(c:Canvas,cx:Float,cy:Float,r:Float){val ms=elapsed();val total=ms/1000;val tenth=(ms/100)%10;val ss=total%60;val mm=(total/60)%60;val hh=total/3600;if(!ambient){crest(c,cx,cy-r*.73f,r);label(c,"PARAMEDIC",cx,cy-r*.38f,r*.060f,text,true);label(c,displayName.uppercase(Locale.getDefault()),cx,cy-r*.27f,r*.085f,accent,true);digitalClock(c,cx,cy+r*.13f,String.format(Locale.getDefault(),"%02d:%02d:%02d.%d",hh,mm,ss,tenth),"HR   MIN   SEC   1/10");button(c,cx-r*.28f,cy+r*.49f,r*.245f,if(running)"Ⅱ PAUSE" else "▶ START");button(c,cx+r*.28f,cy+r*.49f,r*.245f,"↻ RESET");battery(c,cx-r*.30f,cy+r*.75f,"WATCH",watchBattery);battery(c,cx+r*.30f,cy+r*.75f,"PHONE",phoneBattery)};second(c,cx,cy,r,(total%60)*6f);hub(c,cx,cy,r)}
 private fun button(c:Canvas,x:Float,y:Float,w:Float,s:String){val r=min(width,height)*.495f;polygonPanel(c,x-w,y-r*.12f,x+w,y+r*.12f);label(c,s,x,y+r*.025f,r*.064f,accent,true)}
 private fun label(c:Canvas,s:String,x:Float,y:Float,z:Float,col:Int,bold:Boolean=false){paint.shader=null;paint.style=Paint.Style.FILL;paint.typeface=Typeface.create(Typeface.create("sans-serif-condensed",Typeface.NORMAL),if(bold)Typeface.BOLD else Typeface.NORMAL);paint.textAlign=Paint.Align.CENTER;paint.textSize=z;paint.color=col;c.drawText(s,x,y,paint)}
 private fun hand(c:Canvas,cx:Float,cy:Float,len:Float,d:Float,w:Float){val a=Math.toRadians((d-90).toDouble());val ex=cx+cos(a).toFloat()*len;val ey=cy+sin(a).toFloat()*len;paint.style=Paint.Style.STROKE;paint.strokeCap=Paint.Cap.SQUARE;paint.strokeWidth=w*1.45f;paint.color=Color.BLACK;c.drawLine(cx,cy,ex,ey,paint);paint.strokeWidth=w*1.1f;paint.color=Color.rgb(100,105,100);c.drawLine(cx,cy,ex,ey,paint);paint.strokeWidth=w*.62f;paint.color=text;c.drawLine(cx,cy,ex,ey,paint)}
 private fun second(c:Canvas,cx:Float,cy:Float,r:Float,d:Float){val a=Math.toRadians((d-90).toDouble());paint.style=Paint.Style.STROKE;paint.strokeCap=Paint.Cap.ROUND;paint.color=if(ambient)text else accent;paint.strokeWidth=r*.014f;c.drawLine(cx-cos(a).toFloat()*r*.12f,cy-sin(a).toFloat()*r*.12f,cx+cos(a).toFloat()*r*.82f,cy+sin(a).toFloat()*r*.82f,paint)};private fun hub(c:Canvas,cx:Float,cy:Float,r:Float){paint.style=Paint.Style.FILL;paint.color=Color.BLACK;c.drawCircle(cx,cy,r*.055f,paint);paint.style=Paint.Style.STROKE;paint.color=if(ambient)text else accent;paint.strokeWidth=r*.016f;c.drawCircle(cx,cy,r*.043f,paint)}
}
